DROP TABLE IF EXISTS Injury;
DROP TABLE IF EXISTS Award;
DROP TABLE IF EXISTS BuzzerBeater;
DROP TABLE IF EXISTS Statistics;
DROP TABLE IF EXISTS Contract;
DROP TABLE IF EXISTS Team;
DROP TABLE IF EXISTS Player;